name: Build Chromium-Wayland x86_64

on: 
  push:
  workflow_dispatch:

jobs:
  Upload-DC-Symbols:
    runs-on:
      - ubuntu-latest

    steps:  
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install packages
        run: |
          mkdir ~/code
          mkdir ~/code/automate
          mkdir ~/code/chromium_git
          cd ~/code
          sudo apt-get install curl file lsb-release procps python3 python3-pip
          curl 'https://chromium.googlesource.com/chromium/src/+/main/build/install-build-deps.py?format=TEXT' | base64 -d > install-build-deps.py
          sudo python3 ./install-build-deps.py --no-arm --no-chromeos-fonts --no-nacl
          python3 -m pip install dataclasses importlib_metadata

      - name: Get Depot Tools
        working-directory: ~/code
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=/home/marshall/code/depot_tools:$PATH

      - name: Create Automation Script
        working-directory: ~/code/automate
        run: |
          wget https://bitbucket.org/chromiumembedded/cef/raw/master/tools/automate/automate-git.py
          echo '#!/bin/bash
            python3 ../automate/automate-git.py --download-dir=/home/marshall/code/chromium_git --depot-tools-dir=/home/marshall/code/depot_tools --no-distrib --no-build' >> ~/code/chromium_git/update.sh
          chmod 755 ~/code/chromium_git/update.sh

      - name: Run Script
        working-directory: ~/code/chromium_git
        run: |
          ./update.sh

# Patch CEF

      - name: Setup Build
        working-directory: ~/code/chromium_git/chromium/src/cef
        run: |
          export GN_DEFINES="use_sysroot=true use_allocator=none symbol_level=1 is_cfi=false use_thin_lto=false"
          ./cef_create_projects.sh

      - name: Build
        working-directory: ~/code/chromium_git/chromium/src
        run: |
          autoninja -C out/Debug_GN_x64 cefsimple chrome_sandbox

# Run script to create binary distribution
# Publish binary distribution